version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: hamlet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hamlet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (optional - for production-like setup)
  backend:
    build: .
    container_name: hamlet-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/hamlet_db?schema=public
      PORT: 4001
      NODE_ENV: production
      CORS_ORIGINS: http://localhost:3000,http://localhost:3001
    ports:
      - "4001:4001"
    volumes:
      - ./logs:/app/logs
    command: npm start

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: hamlet-network
